### PR TITLE
Add columns to textnodes

### PR DESCRIPTION
**Pull request by pletcher**
I wanted to start the process of lining everything up, working from the back-end to the front-end. @lukehollis, I'll be ready to merge as soon as I get the greenlight from you :) And I'll follow up as quickly as I can with updates to https://github.com/cltk/cltk_frontend and https://github.com/cltk/annotations.

This commit begins the consolidating changes that we've been
implementing across the stack to support more robust annotations. It
adds data {JSON}, entityRanges {JSON[]}, inlineStyleRanges {JSON[]}, and
type {string} columns to the textnodes table, bringing textNodes in line
with the abstract block concepts. We have omitted depth {number} and key
{string} columns because they can be inferred from the location and the
id columns, respectively.

### CODE REVIEW

**Comment by lukehollis** [comment]
Seems really good to me--interested to see how this'll integrate with the annotations. Am I understanding correctly that we could store the annotations in the same table at the texts themselves?

**Comment by pletcher** [comment]
I guess we could do that, but I worry that it would get kind of confusing. The main reason for these changes is to make it easy to refer to very specific ranges of text (even more granular than `textnodes.location`). The annotations themselves can still be stored/searched over on the annotations server, but these changes should make it easier to send that server the right information -- and in turn make it easier to render annotations in the reading environment.

I guess it might be possible to consolidate the two databases at some point, especially if they continue to line up so well. It's an interesting question from lots of angles: to what extent is a text a series of annotations (and vice versa)?

**Comment by lukehollis** [comment]
Ah, that makes more sense to me--yep, the updates addressing very specific ranges of text sound great!  I still like the idea of keeping the annotations in a separate database as well. It seems like the textnodes/blocks are close enough to draft both ways, that you're right that they're getting so close as to be relatively interoperable schema-wise... hrmm..

**Comment by pletcher** [comment]
Hm :/

I've been thinking about this for a bit, and I agree, I think the convergence is probably natural and okay. Do you think we should hold off on this PR for now? (I don't have write access to this repo yet, but I defer to you for the best way to proceed.)

I guess I like the idea of keeping the texts database "pure" so that it can be multipurpose. The annotations database could, conceivably, contain nested annotations (if someone comments on another annotation, for example).

The problem I'm coming up against is one that we've talked about a lot: how to reliably store a note's location. Draft has a really nice way of doing that with the entityMap and each block's entityRanges[], so essentially what this separation between texts and annotations does is put the blocks/textnodes on one server and the entityMap on another. The entityMap just so happens to contain more blocks that look like textnodes -- maybe I'm being obtuse :/

**Pull request merged**
